### ISSUE TITLE
US-Operational-Scenarios-on-Utrecht-Amsterdam Prio: 900

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/product-backlog#61] opened 2015-01-07 15:09 UTC
As an operator (WP1) I want the model of the third iteration to be verified and validated against the following use cases

https://github.com/openETCS/modeling/labels/US-Operational%20Scenarios%20on%20Utrecht%20Amsterdam

**Comment by BaseliyosJacob** [comment] 2015-01-07 15:15
User stories should be considered by WP 4

**Comment by MarcBehrens** [comment] 2015-06-19 06:55
relates to #62

**Comment by mahlmann** [comment] 2015-06-19 07:50
duplicate of #61 . closed.

**Closed** 2015-06-19 07:50 UTC
Labels: Owner WP4, Stakeholder WP3
